# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 郝洁的小栈
subtitle: shaun web
description: web开发
keywords: 前端博客,JavaScript,html5,css3,Jquery,NodeJs,Ubuntu（#博客关键字）
author: 郝洁
language: zh-CN
timezone:


# URL 网站
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://onlyH.github.io
root: /
#: :year/:month/:day/:title/
#permalink_defaults:
permalink: post/:abbrlink.html # post为自定义前缀
abbrlink:
  alg: crc32   #算法： crc16(default) and crc32
  rep: hex     #进制： dec(default) and hex

# Directory 目录配置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md


# Writing 文章
new_post_name: :title.md # File name of new posts新建文件默认文件名
default_layout: post #默认布局
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: next
#theme: next-reloaded
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/onlyH/onlyH.github.io.git
  branch: master

# Extensions
## Plugins: http://hexo.io/plugins/
Plugins: hexo-generate-feed
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 文章末尾添加“本文结束”标记
passage_end_tag:
  enabled: true

  # Post wordcount display settings
  # Dependencies: https://github.com/willin/hexo-wordcount
  post_wordcount:
    item_text: true
    wordcount: true
    min2read: true

    # Live2D
    ## https://github.com/EYHN/hexo-helper-live2d
    ## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
    live2d:
      enable: true
      #enable: false
      scriptFrom: local # 默认
      pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
      pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
      pluginModelPath: assets/ # 模型文件相对与插件根目录路径
      # scriptFrom: jsdelivr # jsdelivr CDN
      # scriptFrom: unpkg # unpkg CDN
      # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
      debug: false # 调试, 是否在控制台输出日志
      model:
        use: live2d-widget-model-hibiki
        # use: live2d-widget-model-wanko # npm-module package name
        # use: wanko   # 博客根目录/live2d_models/ 下的目录名
        # use: ./wives/wanko # 相对于博客根目录的路径
        # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
      display:
        position: right
        width: 145
        height: 315
      mobile:
        show: true # 是否在移动设备上显示
        scale: 0.5 # 移动设备上的缩放
      react:
        opacityDefault: 0.7
        opacityOnHover: 0.8

excerpt:
  depth: 3
  excerpt_excludes: [ ]
  more_excludes: [ ]
  hideWholePostExcerpts: true

  douban:
    movies_img: https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/movie.jpg
    books_img: https://fastly.jsdelivr.net/npm/blog-gallery@1.0.0/1/20200206161657.webp
    id: 228172215
    builtin: false
    item_per_page: 10
    book:
      path: books/index.html
      title: 'This is my book title'
      quote: 'This is my book quote'
      option:
    movie:
      path: movies/index.html
      title: 'This is my movie title'
      quote: 'This is my movie quote'
      option:
    game:
      path: games/index.html
      title: 'This is my game title'
      quote: 'This is my game quote'
      option:
    song:
      path: songs/index.html
      title: 'This is my song title'
      quote: 'This is my song quote'
      option:
    timeout: 10000

